---
  - hosts: web
    remote_user: root
    tasks:
      - yum: 
          name: httpd
          state: installed
      - lineinfile:
          path: /etc/httpd/conf/httpd.conf
          regexp: '^Listen'
          line: 'Listen 8080'
        notify:
          - restart_httpd
      - service:
          name: httpd
          state: restarted
          enabled: yes
      - shell: 
          echo welcome to ansible > /var/www/html/index.html
    handlers:
      - name: restart_httpd
        service:
          name: httpd
          state: restarted
