---
- hosts: web1
  remote_user: root
  vars:
    a: [a,b,c]
    nm: [1,2,3]
  tasks:
    - shell: echo "{{item}}" >> /root/test.txt
      with_nested:
        - "{{a}}"
        - "{{nm}}"
    - shell: cat /root/test.txt
